#!/bin/bash

# LiqPass Insurance Backend Manual Test Script
# This script provides curl commands to test the complete insurance workflow

set -e

BASE_URL="http://localhost:3001"
INTERNAL_KEY="test-internal-key"
ADMIN_KEY="test-admin-key"

echo "========================================="
echo "LiqPass Insurance Backend Test Script"
echo "========================================="
echo ""
echo "Prerequisites:"
echo "1. Backend server running on $BASE_URL"
echo "2. Database migrated"
echo "3. Environment variables set (INTERNAL_API_KEY, ADMIN_API_KEY)"
echo ""
echo "========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Create Purchase Order${NC}"
echo "POST $BASE_URL/api/insurance/create-order"
echo ""
echo "curl -X POST $BASE_URL/api/insurance/create-order \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"bindId\": \"1\"}'"
echo ""
echo "Expected: Returns purchaseOrderId and id"
echo "Save the 'id' value for next steps"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 2: Bind OKX Order${NC}"
echo "POST $BASE_URL/api/purchase-orders/{id}/bind-okx"
echo ""
echo "Replace {id} with the id from Step 1"
echo ""
echo "curl -X POST $BASE_URL/api/purchase-orders/{id}/bind-okx \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"ordId\": \"test-order-123\", \"instId\": \"BTC-USDT-SWAP\"}'"
echo ""
echo "Expected: {\"ok\": true}"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 3: Mark Order as Paid (Internal)${NC}"
echo "POST $BASE_URL/internal/purchase-orders/{id}/mark-paid"
echo ""
echo "curl -X POST $BASE_URL/internal/purchase-orders/{id}/mark-paid \\"
echo "  -H 'x-internal-key: $INTERNAL_KEY' \\"
echo "  -H 'Content-Type: application/json'"
echo ""
echo "Expected: {\"ok\": true, \"paidAt\": \"...\"}"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 4: Query Purchase Order${NC}"
echo "GET $BASE_URL/api/purchase-orders/{id}"
echo ""
echo "curl $BASE_URL/api/purchase-orders/{id}"
echo ""
echo "Expected: Full purchase order details with okxMeta and paidAt"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 5: Trigger Claim (Integration Test)${NC}"
echo "POST $BASE_URL/internal/claims/onchain-trigger"
echo ""
echo "Replace {purchaseOrderId} with the purchaseOrderId from Step 1"
echo ""
echo "curl -X POST $BASE_URL/internal/claims/onchain-trigger \\"
echo "  -H 'x-internal-key: $INTERNAL_KEY' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"purchaseOrderId\": \"{purchaseOrderId}\","
echo "    \"claimant\": \"0xtest123...\""
echo "  }'"
echo ""
echo "Expected: Status VERIFYING or VERIFIED_PENDING_REVIEW (if jp-verify succeeds)"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 6: Admin - List Claims${NC}"
echo "GET $BASE_URL/admin/claims?status=VERIFIED_PENDING_REVIEW"
echo ""
echo "curl '$BASE_URL/admin/claims?status=VERIFIED_PENDING_REVIEW' \\"
echo "  -H 'x-admin-key: $ADMIN_KEY'"
echo ""
echo "Expected: List of claims pending review"
echo "Save the claimId for next steps"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 7: Admin - Approve Claim${NC}"
echo "POST $BASE_URL/admin/claims/{claimId}/approve"
echo ""
echo "curl -X POST $BASE_URL/admin/claims/{claimId}/approve \\"
echo "  -H 'x-admin-key: $ADMIN_KEY' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"approvedBy\": \"admin-test\"}'"
echo ""
echo "Expected: {\"ok\": true}"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${BLUE}Step 8: Admin - Mark Claim as Paid${NC}"
echo "POST $BASE_URL/admin/claims/{claimId}/mark-paid"
echo ""
echo "CURRENT_TIMESTAMP=\$(date +%s)"
echo ""
echo "curl -X POST $BASE_URL/admin/claims/{claimId}/mark-paid \\"
echo "  -H 'x-admin-key: $ADMIN_KEY' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"multisigTxHash\": \"0xtest-multisig-tx\","
echo "    \"paidAtSec\": '\$CURRENT_TIMESTAMP'"
echo "  }'"
echo ""
echo "Expected: {\"ok\": true}"
echo ""

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}Test Script Complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "Acceptance Criteria Checklist:"
echo "[ ] All 8 steps executed successfully"
echo "[ ] purchase_orders table has okx_meta_json and paid_at"
echo "[ ] insurance_claims table has claim record"
echo "[ ] Claim status flow: VERIFYING → VERIFIED_PENDING_REVIEW → APPROVED → PAID"
echo "[ ] Internal endpoints verify x-internal-key"
echo "[ ] Error handling works (duplicate binding, unauthorized access)"
echo ""
